name: GPT Translate Docs

on:
  issue_comment:
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Translate Docs to Chinese
        if: contains(github.event.comment.body, '/translate-docs')
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-4o"
          inputFiles: "content/**/*.md"
          outputFiles: "content/en/**/*.md"
          languages: "English"